---
- hosts: localhost
  gather_facts: yes
  #  vars:
  #  myhostame: simple-server.local
  #vars_files:
  #  - /root/vars.yml
  become: yes
  tasks:
    - name: Install RPMfusion repositories
      shell: rpm -q rpmfusion-nonfree-release || yum -y install --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm
      args:
        creates: /etc/yum.repos.d/rpmfusion-free.repo
        removes: /etc/centos-release

        #    - name: Remove packages
        #      package:
        #        name:
        #          - sylpheed
        #        state: absent

#    - name: Enable module streams
#      command: dnf module enable -y container-tools virt

    - name: Install packages
      package:
        name:
          - vim
          - screen
          - mdadm
          - usbutils
          - podman
          - podman-docker
          - cockpit-dashboard
          - cockpit-composer
          - cockpit-machines
          - cockpit-podman
          - cockpit-storaged
          - mariadb
        state: present
        
    - name: Force systemd to reread config, enable and start service
      systemd:
        name: cockpit.socket
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: Update packages
      package:
        name: '*'
        state: latest
